"""Fixed broken foreign keys

Revision ID: 18aca20f7887
Revises: 4b3965190243
Create Date: 2018-01-04 17:21:54.558035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18aca20f7887'
down_revision = '4b3965190243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'instance', 'platform', ['platform_id'], ['id'])
    op.create_foreign_key(None, 'instance', 'venueuser', ['venue_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instance', type_='foreignkey')
    op.drop_constraint(None, 'instance', type_='foreignkey')
    # ### end Alembic commands ###
