"""Add platform to instances

Revision ID: 4b3965190243
Revises: 05053a1da502
Create Date: 2018-01-04 16:53:15.310433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3965190243'
down_revision = '05053a1da502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('instance', sa.Column('platform_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'platform_id')
    op.drop_table('platform')
    # ### end Alembic commands ###
