"""Improved queue and added a history table

Revision ID: 78b20c646fdc
Revises: da6709858add
Create Date: 2018-02-27 13:55:08.970798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b20c646fdc'
down_revision = 'da6709858add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('place_in_queue', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instance.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('queue', sa.Column('instance_id', sa.Integer(), nullable=False))
    op.add_column('queue', sa.Column('manual', sa.Boolean(), nullable=False))
    op.add_column('queue', sa.Column('place_in_queue', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'queue', 'instance', ['instance_id'], ['id'])
    op.add_column('song', sa.Column('identifier', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'song', ['identifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song', type_='unique')
    op.drop_column('song', 'identifier')
    op.drop_constraint(None, 'queue', type_='foreignkey')
    op.drop_column('queue', 'place_in_queue')
    op.drop_column('queue', 'manual')
    op.drop_column('queue', 'instance_id')
    op.drop_table('history')
    # ### end Alembic commands ###
