"""Make serverSecret unique

Revision ID: c24aebb0ed4b
Revises: 9b149af68d20
Create Date: 2018-01-23 11:10:24.515495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24aebb0ed4b'
down_revision = '9b149af68d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'instance', ['server_secret'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instance', type_='unique')
    # ### end Alembic commands ###
