"""Make a few more things unique where it makes sense

Revision ID: da6709858add
Revises: c24aebb0ed4b
Create Date: 2018-01-23 11:47:16.433838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6709858add'
down_revision = 'c24aebb0ed4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'platform', ['name'])
    op.create_unique_constraint(None, 'venueuser', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venueuser', type_='unique')
    op.drop_constraint(None, 'platform', type_='unique')
    # ### end Alembic commands ###
