"""'Just add salt'

Revision ID: f76b1db622c7
Revises: 18aca20f7887
Create Date: 2018-01-04 18:16:32.225593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76b1db622c7'
down_revision = '18aca20f7887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venueuser', sa.Column('salt', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venueuser', 'salt')
    # ### end Alembic commands ###
