matrix:
  include:
    - language: java
      jdk: oraclejdk10
      before_script:
      - cd interface
      script:
      - ./gradlew build test
    - language: node_js
      before_install:
      - cd client
